---
title: "test bead identification routine"
author: "Miguel Rodo"
date: "06 June 2019"
output: html_document
params: 
  cluster: FALSE
  save_input_fcs: FALSE
  ind: 1
  fcs: ""
  out_path: NULL
  fn: NULL
---

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup-libraries, include = FALSE}
library(CytoML)
library(CATALYST)
library(openCyto)
library(ggcyto)
```

```{r setup-load_data, include = FALSE}
if(  params$cluster ){
  
      # get vector of absolute file paths to read in 
    path_fcs_folder <- "/scratch/rdxmig002/data/cytof/Normalised/Normalised/"
    path_fcs_file_short_vec <- list.files( path_fcs_folder ) 
    path_fcs_file_short_vec <- path_fcs_file_short_vec[ which( path_fcs_file_short_vec == params$fcs )]
    path_fcs_file_vec <- file.path( path_fcs_folder, path_fcs_file_short_vec )
    path_fcs_file_vec <- path_fcs_file_vec[ stringr::str_detect( path_fcs_file_vec, ".fcs" ) ]
    path_fcs_file_vec <- normalizePath( path_fcs_file_vec )

    
  if( params$save_input_fcs ){
    # read in FCS files and create GatingSet
    ncfs <- read.ncdfFlowSet( path_fcs_file_vec )
    save_ncfs( "/scratch/rdxmig002/data/cytof/Normalised/ncfs" )
  } else{
    ncfs <- load_ncfs( "/scratch/rdxmig002/data/cytof/Normalised/ncfs" )
  }

} else{
  path_pkg <- "C:/Users/migue/Work/PhD/Code/CyTOFACSData-External"
  path_load_gs <- file.path( path_pkg, "inst", "extdata", "gs", "prep_post_trans" )
  gs_prep_trans <- flowWorkspace::load_gs( path_load_gs )
  fcs_name_vec <- purrr::map_chr( 1:length(gs_prep_trans), function(i){
    gs_prep_trans[[i]]@name } )
  gs_ind <- which( fcs_name_vec == params$fcs )
  fr_init <- getData( gs_prep_trans[[gs_ind]] ) 
  fr <- fr_init
  ex <- exprs( fr )
  n_row <- nrow( ex )
  set.seed(1)
  row_sample_vec <- sample.int( n = n_row, size = 1e3, replace = FALSE)
  ex_rep <- ex[row_sample_vec,]
  exprs( fr ) <- ex_rep
}
```

```{r setup-trans, include = FALSE}
trans <- params$cluster
```

# Remove beads

```{r ,results='asis', fig.height = 4, message = FALSE}
if( params$cluster ){
  for( i in 1:1 ){
      fr_init <- ncfs[[i]]
      fr <- fr_init
      ex <- exprs( fr )
      n_row <- nrow( ex )
      set.seed(1)
      row_sample_vec <- sample.int( n = n_row, size = 1e4, replace = FALSE)
      ex_rep <- ex[row_sample_vec,]
      exprs( fr ) <- ex_rep
      fs <- removeBeads( x = fr, y = "dvs", trans = trans, 
                     out_path = "/scratch/rdxmig002/data/cytof/Post_debeading/", 
                     fn = path_fcs_file_short_vec[i], 
                     fn_sep = "/" )  
      }

} else{
  fs <- removeBeads( x = fr, y = "dvs", trans = trans, 
                     out_path = params$out_path, 
                     fn = params$fn )
}
```
