---
title: "Live cells"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:
  cluster: false
  ncfs: false
  save_input: true
  save_output: false
  trans: true
  reduce: true
  only_one: true
---

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", eval = FALSE)
``` 

```{r setup-libraries, include = FALSE, eval = TRUE}
library(CytoML)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)
filter <- flowCore::filter
```

```{r function-getFcsFn}
getFcsFn <- function(fr){
  fn_init <- fr@description$FILENAME
  slash_pos_vec <- stringr::str_locate_all( fn_init, "/")[[1]][,1]
  last_slash_pos <- slash_pos_vec[length(slash_pos_vec)]
  stringr::str_sub( fn_init, last_slash_pos + 1, -5 )
}
```

```{r setup-load_data, include = FALSE, eval = TRUE}
if( params$cluster ){
  
  path_pkg <- "/scratch/rdxmig002/data/cytof"
  path_data <- path_pkg
  if( !params$ncfs ){
    path_fcs_folder <- file.path( path_pkg, "fcs", "debeaded" ) 
    path_fcs_file_short_vec <- list.files( path_fcs_folder ) 
    path_fcs_file_short_ind_vec <- str_detect( path_fcs_file_short_vec, 
                                               "debeaded")
    path_fcs_file_short_vec <- path_fcs_file_short_vec[ path_fcs_file_short_ind_vec ]
    path_fcs_file_vec <- file.path( path_fcs_folder, path_fcs_file_short_vec )
    path_fcs_file_vec <- normalizePath( path_fcs_file_vec )
    if( params$only_one ) path_fcs_file_vec <- path_fcs_file_vec[1]
    # read in FCS files and create GatingSet
    fs <- read.ncdfFlowSet( path_fcs_file_vec )
    if( params$only_one ) fs <- fs[1]
    if( params$save_input ) save_ncfs( fs, file.path( path_pkg, "ncfs", "singlets" ) )
  } else{
    fs <- ncdfFlow::load_ncfs( file.path( path_pkg, "ncfs", "singlets" ) )
    if( params$only_one ) fs <- fs[1]
  }
  
} else{
  path_pkg <- "C:/Users/migue/Work/PhD/Code/CyTOFACSData-External"
  path_data <- file.path( path_pkg, "inst", "extdata" )
  #path_fcs <- file.path( path_pkg, "inst", "extdata", "Normalised", "01_0673 d0 09_0462 d0 _1_1.fcs" )
  #ncfs <- read.ncdfFlowSet( path_fcs )
  #path_ncfs_save <- file.path( path_pkg, "inst", "extdata", "ncfs", "test_live" )
  #ncdfFlow::save_ncfs(ncfs, path = path_ncfs_save )
  path_ncfs_load <- file.path( path_pkg, "inst", "extdata", "ncfs", "test_live" )
  fs <-  ncdfFlow::load_ncfs( path_ncfs_load )
  if( params$only_one ) fs <- fs[1]
}
```

```{r setup-reduce_size_or_transform}
if( params$reduce | params$trans ){
  fs_new <- ncfsApply( fs, function(fr){
    ex <- exprs(fr)
    if( params$reduce ){
      samp <- sample( 1:nrow( ex ), 1e4, replace = FALSE )
      ex <- ex[samp,]
    } else samp <- nrow( ex )
    if( params$trans ) ex <- asinh( ex/5 )
    exprs(fr) <- ex
    fr
  } )
}
```

# Live cells

```{r gate-live}
# Gate live cells using mindensity2 
fs_new_2 <- ncfsApply( fs_new, function(fr){
  ex <- exprs(fr)
  singlets_fc_gate <- flowClust.2d( ex, 
                                    xChannel = "Ir191Di", 
                                    yChannel = "Ir193Di", 
                                    filterId = "singlet_fc",
                                    K = 2, 
                                    quantile = 0.85, 
                                    target = c( 6, 6 ) )
  fr_singlets_fc_gate <- flowCore::filter( fr, singlets_fc_gate)
  ex_singlets_fc <- ex[fr_singlets_fc_gate@subSet,]
  exprs( fr ) <- ex_singlets_fc
  fr
})
```

Gate live cells.
```{r , eval = TRUE}
live_cells_gate <- mindensity2( fr, channel = "Rh103Di", gate_range = c( 3.8, 5.8 ), filterId = "live" )
fr_live_gate <- filter( fr, live_cells_gate)
ex_live <- exprs( fr )[!fr_live_gate@subSet,]
fr_live <- fr
exprs( fr_live ) <- ex_live
```

Plot gates. 
```{r }
x_int <- fr_live_gate@filterDetails$liv$filter@min
ggplot( as.data.frame( ex ), aes( x = Rh103Di ) ) + 
  geom_density() +
  geom_vline( xintercept = x_int, col = 'red' )
```

Save output.  
```{r }
fn_init <- fr_live@description$FILENAME
slash_pos_vec <- stringr::str_locate_all( fn_init, "/")[[1]][,1]
last_slash_pos <- slash_pos_vec[length(slash_pos_vec)]
fn_temp <- stringr::str_sub( fn_init, last_slash_pos + 1, -5 )
fn_final <- paste0( fn_temp, "-live.fcs" )
path_save <- file.path( path_pkg, "inst", "extdata", "fcs", "live", fn_final )
flowCore::write.FCS( fr_live, path_save )
```

# Debarcode - Normalisation First

## Barcode-specific cutoffs

### Assign to barcode pairs.

```{r bc-f-s-pairs}
# create initial db_frame object
re0 <- assignPrelim( x = fr, y = db_tbl, verbose = TRUE, 
                     trans = FALSE, norm_first = TRUE )
```

#### Estimate cutoffs. 

```{r bc-f-s-est}
# estimate cutoffs
re <- estCutoffs( x = re0 )
```

#### Apply cutoffs. 

```{r bc-f-s-apply}
# apply cutofs
mhl_cutoff( re ) <- 5
re <- applyCutoffs( x = re, sep = 0.25 )
```

#### Write FCS

```{r bc-f-s-out}
out_nms <- stringr::str_c( stringr::str_sub( gs_test[[1]]@name, end = -5 ), "-", names( re@sep_cutoffs ) )
out_path <- file.path( path_pkg, "inst", "extdata", "debarcoded" )
outFCS( x = re, y = fr, out_path = out_path, out_nms = out_nms )
```

# Live cells

Get vector of absolute paths to all the FCS files to read in.

```{r live-path}
path_fcs_folder <- file.path( path_pkg, "inst", "extdata", "debarcoded" ) 
path_fcs_file_short_vec <- list.files( path_fcs_folder ) 
path_fcs_file_vec <- file.path( path_fcs_folder, path_fcs_file_short_vec )
path_fcs_file_vec <- path_fcs_file_vec[ stringr::str_detect( path_fcs_file_vec, ".fcs" ) ]
path_fcs_file_vec <- path_fcs_file_vec[ !stringr::str_detect( path_fcs_file_vec, "Unassigned" ) ]
path_fcs_file_vec <- normalizePath( path_fcs_file_vec )
```

Read in FCS files and create `GatingSet`. 
```{r  prep-full-read}
ncfs <- read.ncdfFlowSet( path_fcs_file_vec )
gs_post_bc <- GatingSet( ncfs )
```

Save `GatingSet` object. 
```{r  prep-full-save}
path_save_gs <- file.path( path_pkg, "inst", "extdata", "gs", "post-debarcoding" )
save_gs( gs_post_bc, path = path_save_gs )
```

```{r }
# setNode( gs_debeaded, "live_cells", FALSE )
add_pop( gs_post_bc, alias = "live_cells", pop = "-", gating_method = "mindensity2", parent = "root", dims = "Livedead", gating_args = "gate_range = c( 100, 130 )" )
```

```{r }
for( i in 1:10 ){
  p0 <- ggcyto( gs_post_bc[1], aes( x = Livedead ), 
        subset = "root" ) + 
  geom_density() +
  geom_gate( "live_cells" )
p1 <- ggcyto( gs_post_bc[1], aes( x = Livedead, y = Ir191Di ), 
        subset = "root" ) +
  geom_hex( bins = 64 ) +
  geom_gate( "live_cells" )
plot_list <- purrr::map( list( p0, p1 ), as.ggplot )
windows()
print( cowplot::plot_grid( plotlist = plot_list, labels = c( "Post beads" ) ) )
}
```

# Singlets

```{r }
setNode( gs_post_bc, "singlets_post_live", FALSE )
add_pop( gs_post_bc, alias = "singlets_post_live", pop = "+", gating_method = "flowClust.2d", parent = "live_cells", dims = "Ir191Di,Ir193Di", gating_args = "K = 2, quantile = 0.90" )
```

## Initial flowClust

```{r }
for( i in 1:10 ){
  p0 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di, y = Ir193Di ), 
        subset = "root" ) +
  geom_hex( bins = 64 ) +
  geom_gate( "singlets_post_live" )
p1 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di, y = Ir193Di ), 
        subset = "live_cells" ) +
  geom_hex( bins = 64 ) +
  geom_gate( "singlets_post_live" )
plot_list <- purrr::map( list( p0, p1 ), as.ggplot )
windows()
print( cowplot::plot_grid( plotlist = plot_list, labels = c( "Post beads" ) ) )
}
```

```{r }
for( i in 1:10 ){
  p0 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di ), 
        subset = "singlets_post_live" ) + 
  geom_density() 
p1 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di ), 
        subset = "live_cells" ) + 
  geom_density() 
plot_list <- purrr::map( list( p0, p1 ), as.ggplot )
windows()
print( cowplot::plot_grid( plotlist = plot_list, labels = c( "Post beads" ) ) )
}
```

## Post-flowClust Clean

```{r }
setNode( gs_post_bc, "singlets_post_fc_dna1", FALSE )
setNode( gs_post_bc, "singlets_post_fc_dna12", FALSE )
add_pop( gs_post_bc, alias = "singlets_post_fc_dna1", pop = "+", gating_method = "mindensity2", parent = "singlets_post_live", dims = "Ir191Di", gating_args = "gate_range = c(0,20)"  )
add_pop( gs_post_bc, alias = "singlets_post_fc_dna12", pop = "+", gating_method = "mindensity2", parent = "singlets_post_live", dims = "Ir193Di", gating_args = "gate_range = c(0,20)"  )

add_pop( gs_post_bc, alias = "singlets_post_fc_dna1", pop = "-", gating_method = "mindensity2", parent = "singlets_post_live", dims = "Ir191Di", gating_args = "gate_range = c(100,200)"  )
add_pop( gs_post_bc, alias = "singlets_post_fc_dna12", pop = "-", gating_method = "mindensity2", parent = "singlets_post_live", dims = "Ir193Di", gating_args = "gate_range = c(100,200)"  )
# high gate
add_pop( gs_post_bc, alias = "singlets_post_fc_dna1", pop = "-", gating_method = "tailgate", parent = "singlets_post_live", dims = "Ir191Di", gating_args = "method = 'second_deriv'"  )
add_pop( gs_post_bc, alias = "singlets_post_fc_dna12", pop = "-", gating_method = "tailgate", parent = "singlets_post_fc_dna1", dims = "Ir193Di", gating_args = "method = 'second_deriv'"  )
```

```{r }
for( i in 1:10 ){
  p0 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di ), 
        subset = "singlets_post_live" ) + 
  geom_density() +
    geom_gate( "singlets_post_fc_dna1" )
p1 <- ggcyto( gs_post_bc[1], aes( x = Ir193Di ), 
        subset = "singlets_post_live" ) + 
  geom_density() +
  geom_gate( "singlets_post_fc_dna12" )
plot_list <- purrr::map( list( p0, p1 ), as.ggplot )
windows()
print( cowplot::plot_grid( plotlist = plot_list, labels = c( "Post beads" ) ) )
}
```

```{r }
for( i in 1:10 ){
  p0 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di, y = Ir193Di ), 
        subset = "singlets_post_fc_dna12" ) +
  geom_hex( bins = 64 )
p1 <- ggcyto( gs_post_bc[1], aes( x = Ir191Di, y = Ir193Di ), 
        subset = "live_cells" ) +
  geom_hex( bins = 64 )
plot_list <- purrr::map( list( p0, p1 ), as.ggplot )
windows()
print( cowplot::plot_grid( plotlist = plot_list, labels = c( "Post beads" ) ) )
}
```
