---
title: "Singlets"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:
  cluster: true
  ncfs: true
  save_input: false
  save_output: true
  trans: true
  reduce: true
  ind: 74
---

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", message = FALSE, warning = FALSE)
``` 

```{r setup-libraries, include = FALSE}
library(CytoML)
# library(CATALYST)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)
devtools::load_all()
```

```{r bv-gradient}
# bivariate
get_rgb_col <- function( red, green, blue ){
  rgb( red = red / 256, green = green / 256, blue = blue / 256 )
}
grad_col_vec <- purrr::map_chr( list( c( 239, 243, 255 ), 
                                      c( 189, 215, 231 ), 
                                      c( 107, 174, 214 ), 
                                      c( 49, 130, 189 ), 
                                      c( 8, 81, 156 ),
                                      c( 5, 75, 134 ),
                                      c( 3, 70, 120 ) ), 
                                function(x){
                                  get_rgb_col( x[[1]], x[[2]], x[[3]])
                                } )
if( !params$reduce ){
  breaks <- c( 0, 1, 100, 1e4, 1e6)
} else{
  breaks <- c( 0, 1, 10, 100, 1e3 )
}
```

```{r setup-data}
dir_base <- "C:/Users/migue/OneDrive - University of Cape Town/Work/PhD/Data/Missing Normalised CyTOF Data"
dir_ncfs_debeaded <- file.path(dir_base, "debeaded", "ncfs")
fs_debeaded <- load_ncfs(dir_ncfs_debeaded)
```

```{r setup-reduce_size_or_transform}
if(params$reduce | params$trans){
  fs_debeaded <- ncfsApply(fs_debeaded, function(fr){
    ex <- exprs(fr)
    if(params$reduce){
      samp <- sample(1:nrow(ex), min(nrow(ex), 1e4), replace = FALSE)
      ex <- ex[samp,]
    }
    if(params$trans ) ex <- asinh(ex/5)
    exprs(fr) <- ex
    fr
  })
}
```

# Singlets 

## Elliptical gates

```{r gate-fc}
# Gate singlets using `flowClust.2d`. 
fs_ellipse <- ncfsApply(fs_debeaded, function(fr){
  fn <- fr@description$FILENAME
  ex <- exprs(fr)
  if( stringr::str_detect( fn, "miguel-concat-replace-04_0333" ) ){
    ex_ind_1 <- ex[,"Ir191Di"] > 2 & ex[,"Ir191Di"] < 6
	  ex_ind_3 <- ex[,"Ir193Di"] > 2 & ex[,"Ir193Di"] < 6
	  ex_ind <- ex_ind_1 & ex_ind_3
	  exprs( fr ) <- ex[ex_ind,]
  } else{
    #debugonce(openCytoFork::flowClust.2d)
    #debugonce(openCytoFork::gate_flowclust_2d)
	singlets_fc_gate <- openCytoFork::flowClust.2d( ex, 
                                      xChannel = "Ir191Di", 
                                      yChannel = "Ir193Di", 
                                      filterId = "singlet_fc",
                                      K = 2, 
                                      quantile = 0.85, 
                                      target = c( 6, 6 ), 
                                      eigen_stretch = c(1,30))
	fr_singlets_fc_gate <- flowCore::filter(fr, singlets_fc_gate)
	ex_singlets_fc <- ex[fr_singlets_fc_gate@subSet,]
	exprs( fr ) <- ex_singlets_fc
  }
  fr
})
```
 
```{r plot-bv,results='asis', fig.height = 3}
library(cowplot)
plot_list <- map(seq_along(fs_ellipse), function(i){
  fr <- fs_ellipse[[i]]
  
  ex <- exprs(fr)
  title <- getFcsFn(fr)
  
  ex_old <- exprs( fs_debeaded[[i]] )
  cat("\n")
  cat(paste("The yield is", round(nrow(ex)/nrow(ex_old),2)*100, "%.	"))
  cat("\n")
  xlim <- range( ex_old[,"Ir191Di"] ) 
  ylim <- range( ex_old[,"Ir193Di"] )
  p0 <- ggplot( as.data.frame( ex_old ), aes( x = Ir191Di, 
                                              y = Ir193Di ) ) + 
    geom_hex( bins = 128, show.legend = FALSE ) +
    expand_limits( x = c( 0, max( ex[,"Ir191Di"] ) ), 
                   y = c( 0, max( ex[,"Ir193Di"] ) ) ) +
    scale_fill_viridis_c(trans = 'log10') +
    #scale_fill_gradientn( trans = "log10", 
    #                      breaks = breaks,
    #                      colours = grad_col_vec ) +
    lims( x = xlim, y = ylim ) +
    background_grid()
  p1 <- ggplot( as.data.frame( ex ), aes( x = Ir191Di, 
                                         y = Ir193Di ) ) + 
    geom_hex( bins = 128, show.legend = FALSE ) +
    expand_limits( x = c( 0, max( ex[,"Ir191Di"] ) ), 
                   y = c( 0, max( ex[,"Ir193Di"] ) ) ) +
    scale_fill_viridis_c(trans = 'log10') +
    lims( x = xlim, y = ylim ) +
    background_grid()
  structure( list(p0,p1), title = title ) })
lab_vec <- c( "Parent pop.", "Gated pop." )

walk( plot_list, function(x){
  cat("\n")
  pander::pandoc.header( attr(x,"title" ), level = 3 )
  cat("\n")
  p <- cowplot::plot_grid(plotlist = x, ncol = 2, labels = lab_vec, hjust = -0.75 )
  print(p) 
  cat("\n")
})
```

## Univariate gates

```{r gate-uni-plot_uni, fig.height = 10}
file_vec <- c("07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs",
              "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs")
plot_var_vec <- c("Ir191Di", "Ir193Di")
restriction_tbl <- tibble(file = rep(file_vec, each = 2), 
                          plot_var = rep(plot_var_vec, 2), 
                          min = c(3.75, 4.25, 3.2, 3.5), 
                          max = c(4.9, 5.5, 4.4, 5))
plot_list_hist <- map(1:2, function(i){
  #print(i)
  fr <- fs_ellipse[[i]]
  ex <- exprs(fr)
  #sample_vec <- sample.int(dim(ex)[[1]], 1e4)
  #ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])[sample_vec,]
  ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])
  title <- switch(as.character(i), 
                  "3" = fr@description$GUID,
                  '2' = fr@description$FILENAME %>% str_sub(start = 108),
                  '1' = fr@description$FILENAME %>% str_sub(start = 108))
  #print(title)
  
  map(c("Ir191Di", "Ir193Di"), function(plot_var){
      ggplot(ex_plot, 
             aes(x = !!ensym(plot_var))) +
        geom_histogram(bins = 100, fill = 'gray85', col = 'black') + 
          labs(title = title) + 
          scale_x_continuous(limits = c(0, 9)) +
          geom_vline(data = restriction_tbl %>% dplyr::filter(.data$plot_var == .env$plot_var & 
                                                         file == title), 
                     aes(xintercept = min), col = "red", size = 1) +
                geom_vline(data = restriction_tbl %>% dplyr::filter(.data$plot_var == .env$plot_var & 
                                                         file == title), 
                     aes(xintercept = max), col = "red", size = 1) +
          theme_cowplot() +
          background_grid(major = 'xy')
  })
}) %>%
  flatten()
cowplot::plot_grid(plotlist = plot_list_hist, ncol = 1)
```

```{r gate-uni-plot_bv, fig.height = 10}
plot_list_hex <- map(1:2, function(i){
  #print(i)
  fr <- fs_ellipse[[i]]
  ex <- exprs(fr)
  #sample_vec <- sample.int(dim(ex)[[1]], 1e4)
  #ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])[sample_vec,]
  ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])
  title <- switch(as.character(i), 
                  "3" = fr@description$GUID,
                  '2' = fr@description$FILENAME %>% str_sub(start = 108),
                  '1' = fr@description$FILENAME %>% str_sub(start = 108))
  #print(title)
  ggplot(ex_plot, 
        aes(x = Ir191Di, y = Ir193Di)) + 
    geom_hex() + 
    scale_fill_viridis_c(trans = 'log10') +
    labs(title = title) + 
    coord_equal(xlim = c(2.5,7.5), ylim = c(2.5,7.5)) +
    #geom_abline(slope = -1, intercept = 6, size = 1, col = 'red') +
    #geom_abline(slope = 1, intercept = 1.25, col = "red", size = 1) + 
    #geom_abline(slope = 1, intercept = 0, col = "red", size = 1) + 
    geom_vline(data = restriction_tbl %>% 
                 dplyr::filter(file == title & 
                                 plot_var == "Ir191Di"), 
               aes(xintercept = max), col = "red", size = 1) +
    geom_vline(data = restriction_tbl %>% 
                 dplyr::filter(file == title & 
                                 plot_var == "Ir191Di"), 
               aes(xintercept = min), col = "red", size = 1) +
   geom_hline(data = restriction_tbl %>% 
                dplyr::filter(file == title & 
                            plot_var == "Ir193Di"), 
            aes(yintercept = max), col = "red", size = 1) +
   geom_hline(data = restriction_tbl %>% 
                dplyr::filter(file == title & 
                            plot_var == "Ir193Di"), 
            aes(yintercept = min), col = "red", size = 1) +
    theme_cowplot() +
    background_grid(major = 'xy')
})
cowplot::plot_grid(plotlist = plot_list_hex, ncol = 1)
```

```{r gate_uni-gate}
fs_singlets <- ncfsApply(fs_ellipse, function(fr){
  title <- fr@description$FILENAME %>% str_sub(start = 108)
  ex <- exprs(fr) %>% as_tibble()
  rest_tbl_curr <- restriction_tbl %>%
    dplyr::filter(file == title)
  ex %<>% 
    dplyr::filter(Ir191Di > rest_tbl_curr$min[1] & Ir191Di < rest_tbl_curr$max[2], 
           Ir193Di > rest_tbl_curr$min[2] & Ir193Di < rest_tbl_curr$max[2])
  exprs(fr) <- as.matrix(ex)
  fr
})
```

```{r out-trans}
# params$save_output}
# back transform
if(params$trans){
  fs_singlets <- ncfsApply(fs_singlets, function(fr){
    ex <- exprs(fr)
    ex <- 5 * sinh(ex)
    exprs(fr) <- ex 
    fr
  })
}
```

```{r save-ncfs}
#params$save_output}
# save output files as ncdf
path_ncfs_save <- file.path(dir_base, "singlets", "ncfs")
path_fcs_save <- file.path(dir_base, "singlets", "fcs")
if(!dir.exists(path_ncfs_save)) dir.create(path_ncfs_save, recursive = TRUE)
if(!dir.exists(path_fcs_save)) dir.create(path_fcs_save, recursive = TRUE)
for(i in seq_along(fs_singlets)){
  fr <- fs_singlets[[i]]
  write.FCS(x = fr, filename = file.path(path_fcs_save, 
                                         fr@description$FILENAME %>% 
                                           str_sub(start = 108)))
}
ncdfFlow::save_ncfs(fs_singlets, path_ncfs_save, overwrite = TRUE)
```