---
title: "Singlets"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:
  cluster: true
  ncfs: true
  save_input: false
  save_output: false
  trans: false
  reduce: true
  ind: NULL
---

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", message = FALSE, warning = FALSE)
``` 

```{r setup-libraries, include = FALSE}
library(CytoML)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)
```

```{r function-getFcsFn}
getFn <- function(x){
  if( isClass( x, 'flowFrame' ) ) x <- x@description$FILENAME
  slash_pos_vec <- stringr::str_locate_all( x, "/")[[1]][,1]
  last_slash_pos <- slash_pos_vec[length(slash_pos_vec)]
  x <- stringr::str_sub( x, last_slash_pos + 1, -5 )
  if( stringr::str_sub( x, start = -3 ) == "fcs" ) x <- stringr::str_sub( x, end = -5 )
  x 
}
```

```{r bv-gradient}
# bivariate
get_rgb_col <- function( red, green, blue ){
  rgb( red = red / 256, green = green / 256, blue = blue / 256 )
}
grad_col_vec <- purrr::map_chr( list( c( 239, 243, 255 ), 
                                      c( 189, 215, 231 ), 
                                      c( 107, 174, 214 ), 
                                      c( 49, 130, 189 ), 
                                      c( 8, 81, 156 ),
                                      c( 5, 75, 134 ),
                                      c( 3, 70, 120 ) ), 
                                function(x){
                                  get_rgb_col( x[[1]], x[[2]], x[[3]])
                                } )
if( !params$reduce ){
  breaks <- c( 0, 1, 100, 1e4, 1e6)
} else{
  breaks <- c( 0, 1, 10, 100, 1e3 )
}
```

```{r setup-load_data, include = FALSE}
if( params$cluster ){
  
  path_data <- "/scratch/rdxmig002/data/cytof"
  path_in <- file.path( path_data, "ncfs", "singlets" ) 
  path_ncfs_dirs_vec <- list.dirs( path_in ) 
  if( !is.null( params$ind ) ) path_ncfs_dirs <- path_ncfs_dirs_vec[params$ind]
  if( !params$ncfs ){
    stop( "Code not set up for params$ncfs == FALSE" )
    path_fcs_file_vec <- file.path( path_fcs_folder, path_fcs_file_short_vec )
    path_fcs_file_vec <- normalizePath( path_fcs_file_vec )
    # read in FCS files and create GatingSet
    fs <- read.ncdfFlowSet( path_fcs_file_vec )
    if( params$save_input ){
		if( !is.null( params$ind ) ){
		  fn <- stringr::str_sub( path_fcs_file_short_vec, end = -5 )
		  save_ncfs( fs, file.path( path_pkg, "ncfs", "debeaded", fn ), 
		             overwrite = TRUE  )	
		} else{
		  save_ncfs( fs, file.path( path_pkg, "ncfs", "debeaded_all" ),
					 overwrite = TRUE )	
		}
			
	}
  } else{
	if( !is.null( params$ind ) ){
		  path_ncfs_load <- path_ncfs_dirs	
		} else{
		  path_ncfs_load <- file.path( path_data, "ncfs", "singlets_all" )		
		}
	fn_save <- getFn( path_ncfs_load )
	fn_save <- stringr::str_replace( fn_save, "singlets", "live" )
	fs <- ncdfFlow::load_ncfs( path_ncfs_load )
  }
  
} else{
  stop( "Code not setup for params$cluster == FALSE" )
  path_pkg <- "C:/Users/migue/Work/PhD/Code/CyTOFACSData-External"
  path_data <- file.path( path_pkg, "inst", "extdata" )
  #path_fcs <- file.path( path_pkg, "inst", "extdata", "Normalised", "01_0673 d0 09_0462 d0 _1_1.fcs" )
  #ncfs <- read.ncdfFlowSet( path_fcs )
  #path_ncfs_save <- file.path( path_pkg, "inst", "extdata", "ncfs", "test_live" )
  #ncdfFlow::save_ncfs(ncfs, path = path_ncfs_save )
  path_ncfs_load <- file.path( path_pkg, "inst", "extdata", "ncfs", "test_live" )
  fs <-  ncdfFlow::load_ncfs( path_ncfs_load )
  if( !is.null( params$ind ) ) fs <- fs[ind]
}
```

```{r setup-reduce_size_or_transform}
if( params$reduce | params$trans ){
  fs_new <- ncfsApply( fs, function(fr){
    ex <- exprs(fr)
    if( params$reduce ){
      samp <- sample( 1:nrow( ex ), 1e4, replace = FALSE )
      ex <- ex[samp,]
    } else samp <- nrow( ex )
    if( params$trans ) ex <- asinh( ex/5 )
    exprs(fr) <- ex
    fr
  } )
} else fs_new <- fs
```

# Live cells 

```{r gate-live,include = FALSE}
set.seed(1)
fs_new_2 <- ncfsApply( fs_new, function(fr){
  ex <- exprs(fr)
  live_gate <- gate_mindensity2( fr, channel = "Rh103Di", 
							     gate_range = c( 3.8, 4.7 ), 
							     filterId = "live" )	
  fr_live_gate <- flowCore::filter( fr, live_gate)
  ex_live <- exprs( fr )[!fr_live_gate@subSet,]
  fr_live <- fr
  exprs( fr_live ) <- ex_live
  fr_live
})
```

## Univariate

```{r plot-uv}
ex_orig <- as.data.frame( exprs(fs_new[[1]]) )
x_int <- max( exprs( fs_new_2[[1]] )[,"Rh103Di"] )
ggplot( ex_orig, aes( x = Rh103Di ) ) + 
  geom_histogram( bins = 50 ) +
  geom_vline( xintercept = x_int, col = 'red', size = 2 )
```

## Bivariate

```{r plot-bv}
ggplot( ex_orig, aes( x = Rh103Di, y = Ir191Di ) ) + 
  geom_hex(bins=64) +
  geom_vline( xintercept = x_int, col = 'red', size = 2 ) +
  scale_fill_gradientn( trans = "log10", 
                          breaks = breaks,
                          colours = grad_col_vec )
```

```{r out-trans,eval = params$save_output}
# back transform
if( params$trans ){
  fs_new_2 <- ncfsApply( fs_new_2, function(fr){
    ex <- exprs( fr )
    ex <- 5 * sinh(ex)
    exprs( fr ) <- ex 
    fr
  })
}
```

```{r save-ncfs,eval=params$save_output}
# save output files as ncdf
if( !is.null( params$ind ) ){
	  path_ncfs_save <- file.path( path_data, "ncfs", "live", fn_save )	
	} else{
	  path_ncfs_save <- file.path( path_data, "ncfs", "live_all" )		
	}
ncdfFlow::save_ncfs( fs_new_2, path_ncfs_save, overwrite = TRUE )
```