---
title: "Debarcode"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:	
  i: 1
  dir_base: "C:/Users/migue/OneDrive - University of Cape Town/Work/PhD/Data/Missing Normalised CyTOF Data"
  trans: true
  reduce: false
---

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", message = FALSE, warning = FALSE)
``` 

```{r setup-libraries, include = FALSE}
library(CytoML)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)
devtools::load_all()
filter <- flowCore::filter
```

```{r setup-data}
dir_ncfs_time <- file.path(params$dir_base, "time", "ncfs")
fs_time <- load_ncfs(dir_ncfs_time)
fr <- fs_time[[params$i]]
ex <- exprs(fr)
```

```{r reduce_and_trans}
# transform and reduce if need be
if(params$reduce){
  samp <- sample(1:nrow(ex), min(nrow(ex), 1e5), replace = FALSE)
  ex <- ex[samp,]
}

if(params$trans) ex <- asinh(ex/5)
exprs(fr) <- ex
```

```{r db_tbl}
# create debarcoding key
rep_1 <- function(x) rep(1,x)
rep_0 <- function(x) rep(0,x)

db_tbl <- data.frame( `113` = c( rep_1(4), rep_0(6) ), 
                          `115` = c( 1, rep_0(3), rep_1(3), rep_0(3) ), 
                          `108` = c( 0, 1, rep_0(2), 1, rep_0(2), rep_1(2), 0 ), 
                          `198` = c( rep_0(2), 1, rep_0(2), 1, 0, 1, 0, 1 ), 
                          `209` = c( rep_0(3), 1, rep_0(2), 1, 0, rep_1(2) ), 
                      check.names = FALSE)

stim_vec <- c( "uns", "p1", "p4", "mtbaux", "ebv")
rownames(db_tbl) <- c(paste0( "pid1_", stim_vec), 
                      paste0( "pid2_", stim_vec))

mass_col_vec <- setNames(RColorBrewer::brewer.pal(length(colnames(db_tbl)),
                                                  "Accent"), 
                         colnames(db_tbl))
```

```{r function-get_quant}
get_quant <- function(mkr, quant, mat){
  mat <- as.matrix(mat%>%select_if(is.numeric))
  c(quantile(mat[,mkr ], quant/2), 
    quantile(mat[,mkr], 1-quant/2))
}
```

# Barcode Assignment

Preliminary barcode assignment. 
```{r prelim_assign,message = FALSE}
re <- assignPrelim(x = fr, y = db_tbl, verbose = TRUE, 
                   trans = FALSE, norm_first = TRUE) 
message("post preliminary assignment")
re
```

Apply cutoffs.
```{r apply_cutoff,message = FALSE}
mhl_cutoff(re) <- 5
re <- applyCutoffs(x = re, sep_cutoff = 0.25)
re
message("post applying cutoffs")
```

```{r setup-range_list}
expr_mat <- exprs(fr)
range_list <- purrr::map(colnames(db_tbl), function(mass){
  expr_mat_curr <- expr_mat[,stringr::str_detect(colnames(expr_mat), mass), drop = TRUE]
  c(min(expr_mat_curr), setNames(quantile(expr_mat_curr, 0.9999), NULL))
}) %>%
  setNames(colnames(db_tbl))
```

# Yields
Below are histograms of the separations of the cells for each barcode group, along with the yield for each separation cutoff. 

```{r bc-f-f-yields}
for(bc in rownames(db_tbl)){
  print(plotYields(x = re, which = bc, plotly = FALSE))
}
```

# Post-debarcoding

# Positive bivariate populations

```{r bc-f-f-dbn-biv, results = 'asis', fig.height = 3}
expr_mat <- exprs(re)
id_vec <- bc_ids(re)
uni_id_vec <- sort( unique(id_vec) )
uni_id_vec <- uni_id_vec[ uni_id_vec != "0"]
get_bc_pair_db_tbl <- function(x){ # get the positive bc markers for a given combo
  curr_row <- which( rownames(db_tbl) == x )
  colnames(db_tbl)[which(db_tbl[curr_row,] == 1)]
}
get_bc_expr_tbl_ind <- function(x){ # get the expr tbl column indices for a given combo of masses
  purrr::map_int(x, function(y) which(stringr::str_detect(colnames(expr_mat), y)))
}
get_bc_expr_tbl <- function(x, expr){
  mass_vec_curr <- get_bc_pair_db_tbl(x)
  expr_ind_vec_curr <- get_bc_expr_tbl_ind(mass_vec_curr)
  expr[,expr_ind_vec_curr]
}
purrr::walk(uni_id_vec, function(id){
  expr_mat_curr <- expr_mat[id_vec == id,]
  expr_mat_curr <- get_bc_expr_tbl(id, expr = expr_mat_curr)
  expr_tbl_curr <- tibble::as_tibble(expr_mat_curr)
  mass_vec <- stringr::str_replace_all(colnames(expr_tbl_curr),
                                        "[[:punct:][:alpha:]]",
                                        "")
  range_list_curr <- list(range_list[[mass_vec[1]]], 
                          range_list[[mass_vec[2]]])
  p0 <- ggplot(expr_tbl_curr, aes(x = !!sym(colnames(expr_tbl_curr)[1]), 
                               y = !!sym(colnames(expr_tbl_curr)[2]))) +
    geom_hex(bins = 128) +
    scale_fill_viridis_b(trans = 'log2') +
    expand_limits(x = range_list_curr[[1]], 
                  y = range_list_curr[[2]]) +
    coord_equal()
  cat("\n")
  pander::pandoc.header(id, level = 3)
  cat("\n")
  print( p0 ) 
  cat("\n")
})
```

# Per-cell barcoding marker expression

```{r bc-f-f-events, fig.height = 4}
purrr::walk(uni_id_vec, function(id) plotEvents(x = re, 
                                                which = id, 
                                                n_events = 25))
```

# All univariate populations

```{r bc-f-f-init_range}
expr_mat <- exprs(re)
range_list <- purrr::map( colnames( db_tbl ), function( mass ){
  expr_mat_curr <- expr_mat[ , stringr::str_detect( colnames( expr_mat ), mass ),drop = TRUE ]
  c( min( expr_mat_curr ), setNames( quantile( expr_mat_curr, 0.9999 ), NULL ) )
} ) %>%
  setNames( colnames( db_tbl ) )
```

```{r bc-f-f-dbn,fig.height = 6, results = 'asis'}
expr_mat <- exprs(re)
plot_list <- purrr::map( colnames( db_tbl ), function( mass ){
  expr_mat_curr <- expr_mat[ , stringr::str_detect( colnames( expr_mat ), mass ),drop = FALSE ]
  expr_tbl_curr <- tibble::as_tibble( expr_mat_curr )
  mass <- stringr::str_replace_all( colnames( expr_tbl_curr ),
                                        "[[:punct:][:alpha:]]",
                                        "")
  ggplot( expr_tbl_curr, aes( x = !!sym( colnames( expr_tbl_curr ) ) ) ) +
    geom_density( fill = mass_col_vec[mass] )
} )
cat("\n")
pander::pandoc.header( "Initial distributions", level = 3 )
cat("\n")
cowplot::plot_grid( plotlist = plot_list, ncol = 2 )
cat("\n")
```

```{r bc-f-f-dbn-uni, fig.height = 2.5, results = 'asis'}
expr_mat <- exprs(re)
id_vec <- bc_ids(re)
uni_id_vec <- sort( unique(id_vec) )
uni_id_vec <- uni_id_vec[ uni_id_vec != "0"]
bc_mass_vec <- colnames( db_tbl )
get_bc_pair_db_tbl <- function( x ){ # get the positive bc markers for a given combo
  curr_row <- which( rownames( db_tbl ) == x )
  colnames( db_tbl )[ which( db_tbl[curr_row,] == 1 ) ]
}
get_bc_expr_tbl_ind <- function( x ){ # get the expr tbl column indices for a given combo of masses
  purrr::map_int( x, function( y ) which( stringr::str_detect( colnames( expr_mat ), y ) ) )
}
get_bc_expr_tbl <- function( x, expr ){
  mass_vec_curr <- get_bc_pair_db_tbl( x )
  expr_ind_vec_curr <- get_bc_expr_tbl_ind( mass_vec_curr )
  expr[,expr_ind_vec_curr ]
}
purrr::walk( uni_id_vec, function(id){
  pos_mass_vec <- get_bc_pair_db_tbl( x = id )
  pos_ind_vec <- purrr::map_int( pos_mass_vec, function( mass ){
    which( bc_mass_vec == mass )
  } )
  neg_ind_vec <- purrr::map( bc_mass_vec, function( mass ){
    if( mass %in% pos_mass_vec ) return( NULL )
    which( bc_mass_vec == mass )
  }) %>%
    purrr::compact() %>%
    unlist()
  ordered_mass_vec <- colnames( db_tbl )[ c( pos_ind_vec, neg_ind_vec )]
  plot_list <- purrr::map( ordered_mass_vec,
                           function(mass){
                             expr_mat_curr <- expr_mat[ id_vec == id, stringr::str_detect( colnames( expr_mat ), mass ),drop = FALSE ]
                             expr_tbl_curr <- tibble::as_tibble( expr_mat_curr )
                            mass <- stringr::str_replace_all( colnames( expr_tbl_curr ),
                                        "[[:punct:][:alpha:]]",
                                        "")
  range_curr <- range_list[[mass]]
                             ggplot( expr_tbl_curr, aes( x = !!sym( colnames( expr_tbl_curr ) ) ) ) +
                               geom_density(fill = mass_col_vec[mass]) +
                               expand_limits( x = range_curr ) +
                               theme( axis.text.x = element_text( angle = 90, 
                                                                  hjust = 1, 
                                                                  size = 8), 
                                      axis.title.y = element_blank(), 
                                      axis.ticks.y = element_blank(), 
                                      axis.text.y = element_blank( ))
                         })

  cat("\n")
  pander::pandoc.header( id, level = 3 )
  cat("\n")
  print( cowplot::plot_grid( plotlist = plot_list, ncol = 3 ) )
  cat("\n")
} )
```

# DNA and Rhodium

```{r function-plot_dna}
plot_dna <- function(ex, id){

  ex_bc <- ex[ id_vec == id, ]
  ex <- ex[sample(1:nrow(ex),nrow(ex)/10),]
  ex_bc_tbl <- tibble::as_tibble( ex_bc ) %>%
    mutate( type = "Post-debarcoding" ) 
  ex_tbl <- tibble::as_tibble( ex ) %>%
    mutate( type = "Pre-debarcoding")
  plot_tbl <- bind_rows( ex_tbl, ex_bc_tbl )
  range_r <- get_quant( 'Rh103Di', 0.001, ex_tbl )
  range_i1 <- get_quant( 'Ir191Di', 0.001, ex_tbl )
  range_i3 <- get_quant( 'Ir193Di', 0.001, ex_tbl )
  p0 <- ggplot( plot_tbl, aes( x = Ir191Di, fill = type ) ) + 
    geom_histogram( bins = 128, position = 'dodge' ) +
    scale_fill_manual( values = c( "Post-debarcoding" = "dodgerblue", 
                       "Pre-debarcoding" = "orange" ) ) +
    theme( legend.title = element_blank() )
  p1 <- ggplot( plot_tbl, aes( x = Ir193Di, fill = type ) ) + 
    geom_histogram( bins = 128, position = 'dodge' ) +
    scale_fill_manual( values = c( "Post-debarcoding" = "dodgerblue", 
                       "Pre-debarcoding" = "orange" ) ) +
    theme( legend.title = element_blank() )
  p2 <- ggplot( ex_bc_tbl, aes( x = Ir191Di,y = Ir193Di ) ) + 
   geom_hex( bins = 128 ) +
    scale_fill_viridis_b(trans = 'log2') +
    expand_limits( x = range_i1, y = range_i3 )
  p3 <- ggplot( ex_bc_tbl, aes( x = Rh103Di,y = Ir193Di ) ) + 
   geom_hex( bins = 128 ) +
	 scale_fill_viridis_b(trans = 'log2') +
    expand_limits( x = range_r, y = range_i3 )
  p4 <- ggplot( plot_tbl, aes( x = Rh103Di, fill = type ) ) + 
    geom_histogram( bins = 128, position = 'dodge' ) +
    scale_fill_manual( values = c( "Post-debarcoding" = "dodgerblue", 
                       "Pre-debarcoding" = "orange" ) ) +
    theme( legend.title = element_blank() )
  
  cat("\n")
  pander::pandoc.header( id, level = 3 )
  cat("\n")
  print( p0 ) 
  cat("\n")
  print( p1 ) 
  cat("\n")
  print( p2 ) 
  cat("\n") 
  print( p3 ) 
  cat("\n") 
  print( p4 ) 
  cat("\n") 
}
```

```{r plot_dna,results='asis'}
ex <- exprs(re)
id_vec <- bc_ids(re)
uni_id_vec <- sort( unique(id_vec) )
uni_id_vec <- uni_id_vec[uni_id_vec != "0"]
id <- uni_id_vec[1]
purrr::walk(uni_id_vec, function(id){
  plot_dna(ex, id)
})
```

```{r out_fcs}
# transform back if need be
if(params$trans) ex <- 5 * sinh(ex)

# save new expression matrix to FlowFrame
exprs(fr) <- ex

# transform back if need be
if(params$trans){
  ex <- exprs(re)
  ex <- 5 * sinh(ex)
  re@exprs <- ex
}

# get file names
fn_base <- fr@description$FILENAME %>% str_sub(start = 104) 
fn_bc_vec <- stringr::str_c(fn_base, "-", rownames(bc_key(re)))

# create folder to save to
dir_fcs_save <- file.path(params$dir_base, "debarcoded", "fcs")
if(!dir.exists(dir_fcs_save)) dir.create(dir_fcs_save, recursive = TRUE)

# save
outFCS(x = re, y = fr, out_path = dir_fcs_save, out_nms = fn_bc_vec) 
```
