---
title: "Clean-up"
author: "Miguel Rodo"
date: "12/12/2019"
output: html_document
---

1. 01-0993 D0 AND 07-1147 DAY0_normalized
    - flowCut effect: minor
    - Manual: no
    - Overall: pass
    - Recalc check: match
2. 04_1104 d0 and d180_2
    - flowCut effect: minor
    - Manual: no 
    - Overall: flag (conv - with sep)
    - Recalc check: match
3. 01_0673 d0 09_0462 d0
    - flowCut effect: significant (improvement)
    - Manual: no 
    - Overall: pass 
    - Recalc check: match
4. 04_1020 D360 and 04_1020 D540
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
    - Recalc check: match
5. 04_1056 d0 and 04_0979 d0
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass 
    - Recalc check: match
6. 07_0561 D0 AND D180_normalized
    - flowCut effect: significant (debatable improvement)
    - Manual: no 
    - Overall: flag (conv and weak cd8 pop) 
    - Recalc check: match
7. 07_0630 D0 AND 07_0630 D180_normalized
    - flowCut effect: minor
    - Manual: no 
    - Overall: fail (weak cd8 pop)
8. 04_1020D0 and 04_1020 D180_normalized
    - flowCut effect: moderate
    - Manual: no 
    - Overall: pass
    - Recalc check: match
9. 01_0782 day0 and day180
    - flowCut effect: moderate (removed small bits regularly)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
10. 04_1056 d180 and 04_0979 d180
    - flowCut effect: moderate (removed small amount of early parts)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
11. 07_0630 d360 and 07_0630 d540
    - flowCut effect: moderate (removed small amount of early parts)
    - Manual: no 
    - Overall: pass
12. 03-0697 D0 and 03-0545 D0
    - flowCut effect: major (removed large late rise)
    - Manual: no 
    - Overall: pass
13. 07_0663 d360 and 07_0663 d540
    - flowCut effect: major (removed early chunk and many streaks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
14. 04_1241 D0 AND 07_0119 D0_normalized
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
    - Recalc check: match
15. 03_0442 D0 and 09_0248 D0
    - flowCut effect: major (removed chunks throughout; debatable)
    - Manual: no 
    - Overall: pass
    - Recalc check: match (but redo and then re-upload)
16. 04_1241 d180 and 07_0119 d180
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
17. 07_0692 D0 AND 04_1058 D0_normalized
    - flowCut effect: moderate (removed regular intervals)
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
18. 03_0448 D0 and 09_0581 D0_normalized
    - flowCut effect: moderate (removed early chunks and streaks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
19. 07_0692 d180 and 04_1058 d180_normalized
    - flowCut effect: moderate (removed streaks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
20. 04-0910 D360 AND 07-1132 D360
    - flowCut effect: moderate (removed early bits)
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
21. 06_0129 d0 and d180_5_1
    - flowCut effect: minor
    - Manual: no 
    - Overall: fail
    - Recalc check: match 
22. 07-0135 DO AND 09-0406 DO
    - flowCut effect: negligible
    - Manual: no 
    - Overall: pass
    - Recalc check: match 
23. 04-1056 D360 PLUS 04-0979 D360
    - flowCut effect: major (removed first half; debatable)
    - Manual: no 
    - Overall: pass
    - Recalc check: match (but redo; no fc) 
24. 07_1003 day360 and day540
    - flowCut effect: minor (a few streaks)
    - Manual: no 
    - Overall: flag (weak CD8 and small CD3 gap)
    - Recalc check: match 
25. 04_0152 d360 and d540
    - flowCut effect: negligible
    - Manual: no (debatable)
    - Overall: flag (debatable - could fail)
    - Recalc check: match
26. 07-0259 D360 and 04-1067 D360
    - flowCut effect: minor
    - Manual: no 
    - Overall: flag (very jumpy)
    - Recalc check: match
27. 040238 d0and d180
    - flowCut effect: minor (early streaks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
28. 07_1115_1_1
    - flowCut effect: negligible
    - Manual: yes (debatable) 
    - Overall: flag (very jumpy)
    - Recalc check: match
29. 04_0511 D0 AND 04_1119 D0
    - flowCut effect: no
    - Manual: no 
    - Overall: pass
    - Recalc check: match
30. 07-0262 D360 AND 540 27NOV2017
    - flowCut effect: negligible
    - Manual: yes (debatable) 
    - Overall: fail
    - Recalc check: match
31. 07_1153 D540 AND 07_0811 D540
    - flowCut effect: negligible
    - Manual: yes
    - Overall: fail
    - Recalc check: match
32. 04_0695 D360 and 04_0695 D540
    - flowCut effect: moderate (removed beginning and end bits)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
33. 07-0262 DO AND D180 24NOV2017
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
    - Recalc check: match
34. 07_1153 D540 AND 07_0811 D540 (duplicate)
    - flowCut effect: negligible
    - Manual: yes (debatable)
    - Overall: flag (conv)
35. 09_0507 d0 09_0587 d0
    - flowCut effect: moderate (removed at regular intervals)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
36. 04_0695 do and d180_4_1
    - flowCut effect: minor
    - Manual: no
    - Overall: flag (conv)
    - Recalc check: match
37. 04-0718 D0 AND 04-0886 D0
    - flowCut effect: minor (removed at end)
    - Manual: no 
    - Overall: pass
38. 04-0718 D180 AND 04-0886 D180
    - flowCut effect: minor (streaks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
39. 07_1158 d360 and 07_1158 d540
    - flowCut effect: moderate (removed low bits at start and a later small chunk)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
40. 07_0060 D360 AND 04_0699 D360
    - flowCut effect: negligible
    - Manual: no 
    - Overall: pass
    - Recalc check: match
41. 04_0718 d360 and 04_0886 d360
    - flowCut effect: moderate (removed smallish chunks throughout)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
42. 09_0314 D0 AND 01_0978 D0
    - flowCut effect: minor (small bit at start)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
43. 07_0150 D0 AND D180_2_1
    - flowCut effect: negligible
    - Manual: no (debatable) 
    - Overall: flag (conv)
    - Recalc check: match
44. 04_0238 d0and d180-2
    - flowCut effect: negligible
    - Manual: no 
    - Overall: pass
    - Recalc check: match
45. 09_0453 d0 and 09_0745 D0
    - flowCut effect: moderate (removed streaks)
    - Manual: no 
    - Overall: flag (conv)
    - Recalc check: match
46. 04_0741_d0 and d180
    - flowCut effect: major (removed many chunks)
    - Manual: no 
    - Overall: pass
    - Recalc check: match
47. 09_0467 d0 and 09_0278 d0
    - flowCut effect: negligible
    - Manual: no 
    - Overall: pass
48. 07_0177 D0 AND 07_0177
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
49. 07_0208 D0 and D540
    - flowCut effect: minor
    - Manual: no 
    - Overall: flag (conv and weak cd8 pop)
50. 04_0779 D0 AND 07_0369 D0
    - flowCut effect: moderate (removed a small chunk earlier on)
    - Manual: no 
    - Overall: flag (very jumpy)
51. 09_0569 D0 and 09_0529 D0
    - flowCut effect: minor (some streaks)
    - Manual: no 
    - Overall: pass
52. 04_0811D180 AND 07_1153 D180
    - flowCut effect: minor
    - Manual: no 
    - Overall: flag (little sep between pos and neg for CD4 and CD3)
53. 07_0214 DE360 and D540
    - flowCut effect: moderate (removed many streaks)
    - Manual: no 
    - Overall: pass
54. 09_0789 D0 AND 09_0712 D0
    - flowCut effect: moderate (removed significant streaking)
    - Manual: no 
    - Overall: pass 
55. 07_0236 D0 AND D180
    - flowCut effect: negligible
    - Manual: no 
    - Overall: pass
56. 04_0843 D0 AND 04_0843 D180
    - flowCut effect: minor (some streaks)
    - Manual: no 
    - Overall: pass
57. 29NOV2017 07-0080D360 AND 07-0080 D540
    - flowCut effect: minor (some streaks)
    - Manual: no 
    - Overall: pass
58. frozen 07_0060 d180 and 04_0699 d180
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
59. 07_0259 d0 and 04_1067 d0
    - flowCut effect: minor (removed early chunks)
    - Manual: no 
    - Overall: pass
60. FROZEN 20FEB TO 09MAR_ 07_1153 D360 AND 07_0811 D360
    - flowCut effect: moderate (removed large early chunk)
    - Manual: no 
    - Overall: pass
61. 30NOV2017 07-0080 DAY0 AND 07-0080 DAY180
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
62. 04_0910 d0 and 07_1132 d0
    - flowCut effect: moderate
    - Manual: no 
    - Overall: pass
63. in beads for 10 days 07-0259 day540 and 04-1067 day 540
    - flowCut effect: negligible
    - Manual: no 
    - Overall: fail (no sep between cd4/cd3 neg and pos)
64. 07_0386 D0 and D540
    - flowCut effect: minor (removed some streaks)
    - Manual: no 
    - Overall: pass
65. 07_0390 D0 and D540_normalized--19-12-12 07h49_Flagged_TFFF
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
66. 04_0910 D540 AND 07_1132 D540
    - flowCut effect: minor
    - Manual: no 
    - Overall: pass
67. miguel-from_r-06_0127 and 06_0127b
    - flowCut effect: major (removed terrible late section)
    - Manual: no 
    - Overall: pass (debatable)
68. 07_0425D0 and D180
    - flowCut effect: negligible
    - Manual: no 
    - Overall: flag (very weak cd8 pos pop)
69. 02-0185 DO AND 09-0296 D0
    - flowCut effect: major (removes almost all events due to CCR5)
    - Manual: no
    - Overall: fail (but may pass without flowCut)
70. 07_0424 d0 and d540
    - flowCut effect: major (removes over half of events)
    - Manual: no
    - Overall: fail (but may pass without flowCut)
71. FROZEN_04_1241 d360 and 07_0119 d360
    - flowCut effect: negligible
    - Manual: no
    - Overall: pass
72. 07-0692 D360 AND 04-1058 D360
    - flowCut: minor (some streaks)
    - Manual: no
    - Overall: pass
73. 04_0152 D0 AND 04_0152 D180
    - flowCut effect: minor
    - Manual: no
    - Overall: pass
74. 04_0843 d360 and 04_0843 d540
    - flowCut effect: minor
    - Manual: no
    - Overall: pass
75. miguel-concat-replace-04_0333_D0_AND_D180
    - flowCut effect: negligible
    - Manual: no
    - Overall: pass
76. FROZEN_07_0060 D0 AND 04_0699D0
    - flowCut effect: minor
    - Manual: no
    - Overall: pass

Note that one sample was duplicated, hence the count of 76. 