---
title: "Live Cells"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:	
  i: 1
  dir_base: "C:/Users/migue/OneDrive - University of Cape Town/Work/PhD/Data/Missing Normalised CyTOF Data"
  trans: true
  reduce: false
---

# `r stringr::str_replace( params$fn, "-2.1GB_singlets", "" )`

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", message = FALSE, warning = FALSE)
``` 

```{r setup-libraries, include = FALSE}
library(CytoML)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)

filter <- flowCore::filter
```

```{r setup-data}
dir_ncfs_singlets <- file.path(params$dir_base, "singlets", "ncfs")
fs_singlets <- load_ncfs(dir_ncfs_singlets)
fr <- fs_singlets[[params$i]]
ex <- exprs(fr)
```

```{r restriction_tbl}
file_vec <- c("07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs",
              "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs")
plot_var_vec <- c("Ir191Di", "Ir193Di")
restriction_tbl <- tibble(file = rep(file_vec, each = 2), 
                          plot_var = rep(plot_var_vec, 2), 
                          min = c(3.75, 4.25, 3.2, 3.5), 
                          max = c(4.9, 5.5, 4.4, 5))
```


```{r setup-reduce_size_or_transform}
# =======================================
# Preparation 
# =======================================

message('post load expression matrix')
# transform and reduce if need be
if(params$reduce){
  samp <- sample(1:nrow(ex), min(nrow(ex), 1e3), replace = FALSE)
  ex <- ex[samp,]
}
message('post reduce')

if(params$trans ) ex <- asinh(ex/5)
message('post trans')

title <- fr@description$FILENAME %>% str_sub(start = 108)
message('post all prep')

# =======================================
# Histogram of initial data
# =======================================

ggplot(as_tibble(ex[,c("Rh103Di"), drop = FALSE]), 
       aes(x = Rh103Di)) +
  geom_histogram(bins = 100, fill = 'dodgerblue', col = 'black') + 
    labs(title = title) + 
    scale_x_continuous(limits = c(0, 9)) +
    theme_cowplot() +
    background_grid(major = 'xy')

message('post init uv plot')

# =======================================
# BV plot with cut line
# =======================================

#message(title)
if(title == "07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs"){
  int  <- 1; m <- 1
} else if(title == "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs"){
  int <- -1; m <- 1.3
}

ggplot(as_tibble(ex[,c("Rh103Di", "Ir191Di"), drop = FALSE]), 
      aes(x = Rh103Di, y = Ir191Di)) + 
  geom_hex() + 
  labs(title = title) + 
  coord_equal(xlim = c(0,7), ylim = c(3,5.5)) +
  theme_cowplot() +
  scale_fill_viridis_c(trans = 'log10') +
  background_grid(major = 'xy') +
  geom_abline(intercept = int, slope = m, col = 'red', size = 1) 

message('post init bv plot')

# =======================================
# Gate
# =======================================

init_n_row <- nrow(ex)
ex <- ex[ex[,"Ir191Di"] > (int + m * ex[,"Rh103Di"]),]
post_n_row <- nrow(ex)
print(paste0(round(post_n_row/init_n_row * 100, 2), "% yield."))
message(paste0(round(post_n_row/init_n_row * 100, 2), "% yield."))
message('post gating')

# =======================================
# Histogram of initial data
# =======================================

ggplot(as_tibble(ex[,c("Rh103Di"), drop = FALSE]), 
       aes(x = Rh103Di)) +
  geom_histogram(bins = 100, fill = 'dodgerblue', col = 'black') + 
    labs(title = title) + 
    scale_x_continuous(limits = c(0, 9)) +
    theme_cowplot() +
    background_grid(major = 'xy')

message('post-gating uv plot')

# =======================================
# BV plot with cut line
# =======================================

#message(title)
if(title == "07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs"){
  int  <- 1; m <- 1
} else if(title == "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs"){
  int <- -1; m <- 1.3
}

ggplot(as_tibble(ex[,c("Rh103Di", "Ir191Di"), drop = FALSE]), 
      aes(x = Rh103Di, y = Ir191Di)) + 
  geom_hex() + 
  labs(title = title) + 
  coord_equal(xlim = c(0,7), ylim = c(3,5.5)) +
  theme_cowplot() +
  scale_fill_viridis_c(trans = 'log10') +
  background_grid(major = 'xy') +
  geom_abline(intercept = int, slope = m, col = 'red', size = 1) 

message('post-gating bv plot')

# =======================================
#  Output
# =======================================

# transform back if need be
if(params$trans) ex <- 5 * sinh(ex)

# save new expression matrix to FlowFrame
exprs(fr) <- ex

# write to FCS file
path_fcs_save <- file.path(params$dir_base, "live", "fcs")
if(!dir.exists(path_fcs_save)) dir.create(path_fcs_save, recursive = TRUE)
write.FCS(x = fr, filename = file.path(path_fcs_save, title))
```
