---
title: "Manual Live Cell Gating"
author: "Miguel Rodo"
date: "06 June 2019"
output: 
  html_document:
    toc: true
params:	
  reduce: true
  fn: "01_0782 day0 and day180 06sep2017_normalized-2.1GB_singlets"
  gate_list: NULL
  dir_in: "/scratch/rdxmig002/data/cytof/ncfs/singlets"
  dir_out: "/scratch/rdxmig002/data/cytof/ncfs/live"
  trans: true
---

# `r stringr::str_replace( params$fn, "-2.1GB_singlets", "" )`

```{r setup, include=FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "#>", message = FALSE, warning = FALSE)
``` 

```{r setup-libraries, include = FALSE}
library(CytoML)
library(openCyto)
library(ggcyto)
library(magrittr)
library(cowplot)
library(stringr)
library(purrr)
library(dplyr)
filter <- flowCore::filter
```

```{r setup-data}
dir_base <- "C:/Users/migue/OneDrive - University of Cape Town/Work/PhD/Data/Missing Normalised CyTOF Data"
dir_ncfs_singlets <- file.path(dir_base, "singlets", "ncfs")
fs_singlets <- load_ncfs(dir_ncfs_singlets)
```

```{r setup-reduce_size_or_transform}
if(params$reduce | params$trans){
  fs_singlets <- ncfsApply(fs_singlets, function(fr){
    ex <- exprs(fr)
    if(params$reduce){
      samp <- sample(1:nrow(ex), min(nrow(ex), 1e4), replace = FALSE)
      ex <- ex[samp,]
    }
    if(params$trans ) ex <- asinh(ex/5)
    exprs(fr) <- ex
    fr
  })
}
```

# Live cells

```{r gate-uni-plot_uni, fig.height = 10}
file_vec <- c("07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs",
              "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs")
plot_var_vec <- c("Ir191Di", "Ir193Di")
restriction_tbl <- tibble(file = rep(file_vec, each = 2), 
                          plot_var = rep(plot_var_vec, 2), 
                          min = c(3.75, 4.25, 3.2, 3.5), 
                          max = c(4.9, 5.5, 4.4, 5))
plot_list_hist <- map(1:2, function(i){
  #print(i)
  fr <- fs_singlets[[i]]
  ex <- exprs(fr)
  #sample_vec <- sample.int(dim(ex)[[1]], 1e4)
  #ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])[sample_vec,]
  ex_plot <- as_tibble(ex[,c("Rh103Di"), drop = FALSE])
  title <- switch(as.character(i), 
                  "3" = fr@description$GUID,
                  '2' = fr@description$FILENAME %>% str_sub(start = 108),
                  '1' = fr@description$FILENAME %>% str_sub(start = 108))
  #print(title)
  
    ggplot(ex_plot, 
           aes(x = Rh103Di)) +
      geom_histogram(bins = 100, fill = 'gray85', col = 'black') + 
        labs(title = title) + 
        scale_x_continuous(limits = c(0, 9)) +
        theme_cowplot() +
        background_grid(major = 'xy')
}) 
cowplot::plot_grid(plotlist = plot_list_hist, ncol = 1)
```

```{r gate-uni-plot_bv, fig.height = 10}
plot_list_hex <- map(1:2, function(i){
  #print(i)
  fr <- fs_singlets[[i]]
  ex <- exprs(fr)
  #sample_vec <- sample.int(dim(ex)[[1]], 1e4)
  #ex_plot <- as_tibble(ex[,c("Ir191Di", "Ir193Di")])[sample_vec,]
  ex_plot <- as_tibble(ex[,c("Rh103Di", "Ir191Di")])
  title <- switch(as.character(i), 
                  "3" = fr@description$GUID,
                  '2' = fr@description$FILENAME %>% str_sub(start = 108),
                  '1' = fr@description$FILENAME %>% str_sub(start = 108))
  #print(title)
  if(title == "07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs"){
    int  <- 1; m <- 1
  } else if(title == "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs"){
    int <- -1; m <- 1.3
  }
  ggplot(ex_plot, 
        aes(x = Rh103Di, y = Ir191Di)) + 
    geom_hex() + 
    scale_fill_viridis_c(trans = 'log10') +
    labs(title = title) + 
    coord_equal(xlim = c(0,7), ylim = c(3,5.5)) +
    theme_cowplot() +
    scale_fill_viridis_b(trans = 'log10') +
    background_grid(major = 'xy') +
    geom_abline(intercept = int, slope = m, col = 'red', size = 1) +
    theme_cowplot() +
    background_grid(major = 'xy')
})
cowplot::plot_grid(plotlist = plot_list_hex, ncol = 1)
```

```{r gate_bv-gate}
fs_live <- ncfsApply(fs_singlets, function(fr){
  title <- fr@description$FILENAME %>% str_sub(start = 108)
  ex <- exprs(fr) %>% as_tibble()
  #print(title)
  if(title == "07_0177 d360 and 07_0177 d540_cells_found_normalized_debeaded.fcs"){
    int  <- 1; m <- 1
  } else if(title == "07_0663 D0 AND 07_0663 D180_cells_found_normalized_debeaded.fcs"){
    int <- -1; m <- 1.3
  }
  
  ex %<>% 
    dplyr::filter(Rh103Di > (int + m * Ir191Di))
  exprs(fr) <- as.matrix(ex)
  fr
})
```

```{r out-trans}
# params$save_output}
# back transform
if(params$trans){
  fs_singlets <- ncfsApply(fs_singlets, function(fr){
    ex <- exprs(fr)
    ex <- 5 * sinh(ex)
    exprs(fr) <- ex 
    fr
  })
}
```

```{r save-ncfs}
#params$save_output}
# save output files as ncdf
path_ncfs_save <- file.path(dir_base, "live", "ncfs")
path_fcs_save <- file.path(dir_base, "live", "fcs")
if(!dir.exists(path_ncfs_save)) dir.create(path_ncfs_save, recursive = TRUE)
if(!dir.exists(path_fcs_save)) dir.create(path_fcs_save, recursive = TRUE)
for(i in seq_along(fs_singlets)){
  fr <- fs_singlets[[i]]
  write.FCS(x = fr, filename = file.path(path_fcs_save, 
                                         fr@description$FILENAME %>% 
                                           str_sub(start = 108)))
}
ncdfFlow::save_ncfs(fs_singlets, path_ncfs_save, overwrite = TRUE)
```
